configMaps:
  config:
    data:
      NODE_ENV: staging

controllers:
  main:
    containers:
      main:
        resources:
          requests:
            cpu: 500m
            memory: 256Mi
          limits:
            cpu: 1
            memory: 1Gi

route:
  main:
    hostnames:
      - myapp.ghostinfra.net
