hotReload:
  enabled: true

previewDatabase:
  enabled: true

configMaps:
  config:
    data:
      NODE_ENV: staging

controllers:
  main:
    containers:
      main:
        env:
          db__connection__database: $(APP_NAME)_preview_$(GITHUB_PR_NUMBER)
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 1
            memory: 1Gi

route:
  main:
    hostnames:
      - myapp-__GITHUB_PR_NUMBER__.ghostinfra.net
