controllers:
  main:
    containers:
      main:
        resources:
          requests:
            cpu: 1
            memory: 512Mi
          limits:
            cpu: 4
            memory: 2Gi

route:
  main:
    enabled: true
    hostnames:
      - myapp.ghostinfra.com
